version: '3'

services:
  #Контейнер с php-fpm
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: myapp/php
    container_name: agroplan
    env_file:
      - .env
    volumes:
      - ./:/data/agroplan
    working_dir: /data/agroplan
    networks:
      - app-network

  #контейне с Nginx
  webserver:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: agroplan_webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/data/agroplan
    networks:
      - app-network

  # PostgreSQL for testing
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
networks:
  app-network:
    driver: bridge
