version: '3'

services:
  #Контейнер с php-fpm
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: myapp/php
    container_name: agroplan
    env_file:
      - .env
    volumes:
      - ./:/data/agroplan
    working_dir: /data/agroplan
    networks:
      - app-network

  #контейне с Nginx
  webserver:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: agroplan_webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/data/agroplan
    networks:
      - app-network
networks:
  app-network:
    driver: bridge