name: "CI"

on:
  pull_request:
    branches:
      - master  # Trigger on PRs targeting master
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # important!

      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**.php"  # You can customize this glob to fit your repo structure
          phpcs_path: php phpcs.phar
          standard: phpcs.xml

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
           echo "APP_ENV=test" > .env
           echo "DATABASE_URL=postgresql://test_user:test_password@db:5432/test_db?serverVersion=14.6&charset=utf8" >> .env

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build the Docker images
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yaml build

      # Set up PHP environment and install dependencies
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, intl, pdo, pdo_pgsql
          ini-values: post_max_size=256M, upload_max_filesize=256M

      # Start all services in background
      - name: Start services
        run: docker-compose up -d

      # Wait for database to be ready

      # Install Composer dependencies inside the app container
      - name: Install Composer inside container
        run: docker-compose exec -T app php composer.phar install --no-interaction

      # Run the tests
      - name: Run Symfony tests
        run: |
          docker-compose run --rm app php bin/console doctrine:database:create --env=test  # Create test DB
          docker-compose run --rm app php bin/console doctrine:schema:update --force --env=test  # Update schema
          docker-compose run --rm app php bin/phpunit  # Run PHPUnit tests

      # Optionally, you can clean up the containers after running tests
      - name: Cleanup
        run: |
          docker-compose down
